# Generated by Django 4.2.7 on 2023-11-30 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PassionPage_Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=25)),
                ('Comment', models.TextField(max_length=270)),
                ('Publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.BooleanField(default=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='PassionPage_Users.post')),
            ],
            options={
                'ordering': ('-Publish',),
            },
        ),
    ]
